// This file is auto-generated by build-icons.ts
// Icon: ArrowRight (solid)
/**
 * xmlns: http://www.w3.org/2000/svg, viewBox: 0 0 24 24, fill: currentColor, aria-hidden: true, data-slot: icon
 */

import { IconBaseProps } from "../icon-base-props.ts";
type ArrowRightProps = IconBaseProps;

export default function ArrowRight({
	size = 45,
	color = "currentColor",
	className = "",

	...rest
}: ArrowRightProps) {
	return (
		<svg
			xmlns="http://www.w3.org/2000/svg"
			fill={color}
			viewBox="0 0 24 24"
			width={size}
			height={size}
			class={className}
			aria-hidden="true"
			data-slot="icon"
			{...rest}
		>
			<path
				fill-rule="evenodd"
				d="M12.97 3.97a.75.75 0 0 1 1.06 0l7.5 7.5a.75.75 0 0 1 0 1.06l-7.5 7.5a.75.75 0 1 1-1.06-1.06l6.22-6.22H3a.75.75 0 0 1 0-1.5h16.19l-6.22-6.22a.75.75 0 0 1 0-1.06Z"
				clip-rule="evenodd"
			/>
		</svg>
	);
}
