// This file is auto-generated by build-icons.ts
// Icon: ArrowTurnUpLeft (solid)
/**
 * xmlns: http://www.w3.org/2000/svg, viewBox: 0 0 24 24, fill: currentColor, aria-hidden: true, data-slot: icon
 */

import { IconBaseProps } from "../icon-base-props.ts";
type ArrowTurnUpLeftProps = IconBaseProps;

export default function ArrowTurnUpLeft({
	size = 45,
	color = "currentColor",
	className = "",

	...rest
}: ArrowTurnUpLeftProps) {
	return (
		<svg
			xmlns="http://www.w3.org/2000/svg"
			fill={color}
			viewBox="0 0 24 24"
			width={size}
			height={size}
			class={className}
			aria-hidden="true"
			data-slot="icon"
			{...rest}
		>
			<path
				fill-rule="evenodd"
				d="M20.239 20.25a.75.75 0 0 1-.75-.75V8.999H5.549l2.47 2.47a.75.75 0 0 1-1.06 1.06l-3.75-3.75a.75.75 0 0 1 0-1.06l3.75-3.75a.75.75 0 1 1 1.06 1.06l-2.47 2.47h14.69a.75.75 0 0 1 .75.75V19.5a.75.75 0 0 1-.75.75Z"
				clip-rule="evenodd"
			/>
		</svg>
	);
}
