// This file is auto-generated by build-icons.ts
// Icon: Pause (solid)
/**
 * xmlns: http://www.w3.org/2000/svg, viewBox: 0 0 24 24, fill: currentColor, aria-hidden: true, data-slot: icon
 */

import { IconBaseProps } from "../icon-base-props.ts";
type PauseProps = IconBaseProps;

export default function Pause({
	size = 45,
	color = "currentColor",
	className = "",

	...rest
}: PauseProps) {
	return (
		<svg
			xmlns="http://www.w3.org/2000/svg"
			fill={color}
			viewBox="0 0 24 24"
			width={size}
			height={size}
			class={className}
			aria-hidden="true"
			data-slot="icon"
			{...rest}
		>
			<path
				fill-rule="evenodd"
				d="M6.75 5.25a.75.75 0 0 1 .75-.75H9a.75.75 0 0 1 .75.75v13.5a.75.75 0 0 1-.75.75H7.5a.75.75 0 0 1-.75-.75V5.25Zm7.5 0A.75.75 0 0 1 15 4.5h1.5a.75.75 0 0 1 .75.75v13.5a.75.75 0 0 1-.75.75H15a.75.75 0 0 1-.75-.75V5.25Z"
				clip-rule="evenodd"
			/>
		</svg>
	);
}
