// This file is auto-generated by build-icons.ts
// Icon: ChartPie (outline)
/**
 * xmlns: http://www.w3.org/2000/svg, fill: none, viewBox: 0 0 24 24, stroke-width: 1.5, stroke: currentColor, aria-hidden: true, data-slot: icon
 */

import { IconBaseProps } from "../icon-base-props.ts";
type ChartPieProps = IconBaseProps;

export default function ChartPie({
	size = 45,
	color = "currentColor",
	className = "",
	strokeWidth = "1.5",
	...rest
}: ChartPieProps) {
	return (
		<svg
			xmlns="http://www.w3.org/2000/svg"
			fill="none"
			viewBox="0 0 24 24"
			stroke-width={strokeWidth}
			stroke={color}
			width={size}
			height={size}
			class={className}
			aria-hidden="true"
			data-slot="icon"
			{...rest}
		>
			<path
				stroke-linecap="round"
				stroke-linejoin="round"
				d="M10.5 6a7.5 7.5 0 1 0 7.5 7.5h-7.5V6Z"
			/>
			<path
				stroke-linecap="round"
				stroke-linejoin="round"
				d="M13.5 10.5H21A7.5 7.5 0 0 0 13.5 3v7.5Z"
			/>
		</svg>
	);
}
