// This file is auto-generated by build-icons.ts
// Icon: ChevronDoubleUp (outline)
/**
 * xmlns: http://www.w3.org/2000/svg, fill: none, viewBox: 0 0 24 24, stroke-width: 1.5, stroke: currentColor, aria-hidden: true, data-slot: icon
 */

import { IconBaseProps } from "../icon-base-props.ts";
type ChevronDoubleUpProps = IconBaseProps;

export default function ChevronDoubleUp({
	size = 45,
	color = "currentColor",
	className = "",
	strokeWidth = "1.5",
	...rest
}: ChevronDoubleUpProps) {
	return (
		<svg
			xmlns="http://www.w3.org/2000/svg"
			fill="none"
			viewBox="0 0 24 24"
			stroke-width={strokeWidth}
			stroke={color}
			width={size}
			height={size}
			class={className}
			aria-hidden="true"
			data-slot="icon"
			{...rest}
		>
			<path
				stroke-linecap="round"
				stroke-linejoin="round"
				d="m4.5 18.75 7.5-7.5 7.5 7.5"
			/>
			<path
				stroke-linecap="round"
				stroke-linejoin="round"
				d="m4.5 12.75 7.5-7.5 7.5 7.5"
			/>
		</svg>
	);
}
